# Kompilace zdrojového kódu pomocí Node.js
FROM node:22-alpine AS build
WORKDIR /app

# Kopírujeme package.json pro instalaci závislostí 
COPY package.json ./

# Přidáme parametr --legacy-peer-deps pro stabilnější instalaci
RUN npm install --legacy-peer-deps --platform=linux --arch=x64

COPY . .
RUN npm run build

# přesun hotových souborů do produkčního Nginx serveru
FROM nginx:alpine
# Zkopírujeme konfiguraci Nginx 
COPY nginx.conf /etc/nginx/nginx.conf
# Zkopírujeme zkompilovaný React kód (složku dist) do složky Nginx
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
